### ISSUE TITLE
Please exclude u/auto-xkcd37

### ISSUE THREAD

**Issue by jamcowl** [benreid24/xkcd_bot#23]
My bot, [u/auto-xkcd37](https://www.reddit.com/user/auto-xkcd37/), links to xkcd#37 in every one of its comments (it posts every few minutes). Having [u/xkcd_stats_bot](https://www.reddit.com/user/xkcd_stats_bot) reply every single time has 2 effects:
1. It vastly increases the spam impact of both bots.
2. It screws with your [stats](http://xkcdredditstats.com/). Currently 48% of all references are to #37 alone.

I think it would be better if [u/auto-xkcd37](https://www.reddit.com/user/auto-xkcd37/) were excluded entirely.

**Comment by benreid24** [comment]
I agree. I've been contemplating it for a while, but if you feel that I should blacklist it then I'll do it

**Comment by benreid24** [comment]
Blacklisted
