### ISSUE TITLE
Unicode isn't being handled properly.

### ISSUE THREAD

**Issue by mrcarriere** [benreid24/xkcd_bot#25]
Taking a guess here, but I don't think the bot is properly handling unicode.

Example: https://www.reddit.com/r/Unity3D/comments/7k61rz/anyone_knows_what_the_hell_are_these_black_lines/drca3ng/

`Title-text: â« When the spacing is tight / And the difference is slight / That's a moirÃ© â«`

**Comment by benreid24** [comment]
Ah, good catch. That's a database error

**Comment by benreid24** [comment]
Fixed text in database. Turns out that particular xkcd comic has an error in the encoding in the xkcd api itself (https://www.reddit.com/r/RelayForReddit/comments/60xui1/xkcd_text_can_get_wonky/)
